# Generated by Django 5.0.3 on 2024-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsfacility',
            options={'verbose_name_plural': 'Sports Facilities'},
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
