# Generated by Django 5.0.3 on 2024-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_booking', '0002_alter_sportsfacility_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='light_on',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
